"""calidad y etiqueta en el historial

Revision ID: ef304d279997
Revises: 43d8f5f41e85
Create Date: 2026-09-20 10:32:14.344422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef304d279997'
down_revision: Union[str, Sequence[str], None] = '43d8f5f41e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognition_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nitidez', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('brillo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tamano_rostro', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confianza_deteccion', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('esperado', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('esperado_persona_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('candidato_correcto', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(
            'fk_recognition_logs_esperado_persona_id',
            'personas',
            ['esperado_persona_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognition_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recognition_logs_esperado_persona_id', type_='foreignkey')
        batch_op.drop_column('candidato_correcto')
        batch_op.drop_column('esperado_persona_id')
        batch_op.drop_column('esperado')
        batch_op.drop_column('confianza_deteccion')
        batch_op.drop_column('tamano_rostro')
        batch_op.drop_column('brillo')
        batch_op.drop_column('nitidez')

    # ### end Alembic commands ###
