"""modelo en el historial de reconocimientos

Revision ID: 43d8f5f41e85
Revises: 9bebc294fe81
Create Date: 2026-09-20 05:44:26.083690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d8f5f41e85'
down_revision: Union[str, Sequence[str], None] = '9bebc294fe81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognition_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelo', sa.String(length=50), server_default='simulated', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognition_logs', schema=None) as batch_op:
        batch_op.drop_column('modelo')

    # ### end Alembic commands ###
