"""usuarios y auditoria

Revision ID: 3601eda36a2e
Revises: 803f3c0384e4
Create Date: 2026-09-20 17:36:34.013864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3601eda36a2e'
down_revision: Union[str, Sequence[str], None] = '803f3c0384e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokens_validos_desde', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("rol IN ('administrador', 'operador', 'consulta')", name='ck_usuarios_rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_email', sa.String(length=254), nullable=True),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('recurso', sa.String(length=30), nullable=True),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.String(length=12), nullable=False),
    sa.Column('detalle', sa.String(length=500), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_created_at'))
        batch_op.drop_index(batch_op.f('ix_auditoria_accion'))

    op.drop_table('auditoria')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
