"""registros de entrenamiento del modelo de probabilidad

Revision ID: 803f3c0384e4
Revises: ef304d279997
Create Date: 2026-09-20 16:10:33.927541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803f3c0384e4'
down_revision: Union[str, Sequence[str], None] = 'ef304d279997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_training_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recognition_log_id', sa.Integer(), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('similitud', sa.Float(), nullable=False),
    sa.Column('calidad_imagen', sa.Float(), nullable=False),
    sa.Column('iluminacion', sa.Float(), nullable=False),
    sa.Column('resultado_real', sa.Boolean(), nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recognition_log_id'], ['recognition_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recognition_log_id')
    )
    with op.batch_alter_table('ml_training_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_training_records_modelo'), ['modelo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_training_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_training_records_modelo'))

    op.drop_table('ml_training_records')
    # ### end Alembic commands ###
