"""tablas iniciales

Revision ID: 9bebc294fe81
Revises: 
Create Date: 2026-09-20 03:43:18.629959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bebc294fe81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consentimiento_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consentimiento_version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_embeddings_persona_id'), ['persona_id'], unique=False)

    op.create_table('recognition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('similitud', sa.Float(), nullable=False),
    sa.Column('distancia', sa.Float(), nullable=False),
    sa.Column('umbral', sa.Float(), nullable=False),
    sa.Column('coincide', sa.Boolean(), nullable=False),
    sa.Column('probabilidad_calibrada', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recognition_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recognition_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recognition_logs_persona_id'), ['persona_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognition_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recognition_logs_persona_id'))
        batch_op.drop_index(batch_op.f('ix_recognition_logs_created_at'))

    op.drop_table('recognition_logs')
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_embeddings_persona_id'))

    op.drop_table('face_embeddings')
    op.drop_table('personas')
    # ### end Alembic commands ###
